[package]
name = "rcli"
version = "0.1.0"
authors = ["Joshua Johnson <haihua.jym@gmail.com>"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
